.PHONY: clean All

All:
	@echo "----------Building project:[ challenge8 - Debug ]----------"
	@cd "challenge8" && "$(MAKE)" -f  "challenge8.mk"
clean:
	@echo "----------Cleaning project:[ challenge8 - Debug ]----------"
	@cd "challenge8" && "$(MAKE)" -f  "challenge8.mk" clean
