.PHONY: clean All

All:
	@echo "----------Building project:[ pchallenge14 - Debug ]----------"
	@cd "pchallenge14" && "$(MAKE)" -f  "pchallenge14.mk"
clean:
	@echo "----------Cleaning project:[ pchallenge14 - Debug ]----------"
	@cd "pchallenge14" && "$(MAKE)" -f  "pchallenge14.mk" clean
