.PHONY: clean All

All:
	@echo "----------Building project:[ pankajsect13chall - Debug ]----------"
	@cd "pankajsect13chall" && "$(MAKE)" -f  "pankajsect13chall.mk"
clean:
	@echo "----------Cleaning project:[ pankajsect13chall - Debug ]----------"
	@cd "pankajsect13chall" && "$(MAKE)" -f  "pankajsect13chall.mk" clean
