.PHONY: clean All

All:
	@echo "----------Building project:[ SOLIDITY123 - Debug ]----------"
	@cd "SOLIDITY123" && "$(MAKE)" -f  "SOLIDITY123.mk"
clean:
	@echo "----------Cleaning project:[ SOLIDITY123 - Debug ]----------"
	@cd "SOLIDITY123" && "$(MAKE)" -f  "SOLIDITY123.mk" clean
