.PHONY: clean All

All:
	@echo "----------Building project:[ inheritance1 - Debug ]----------"
	@cd "inheritance1" && "$(MAKE)" -f  "inheritance1.mk"
clean:
	@echo "----------Cleaning project:[ inheritance1 - Debug ]----------"
	@cd "inheritance1" && "$(MAKE)" -f  "inheritance1.mk" clean
