.PHONY: clean All

All:
	@echo "----------Building project:[ pjmfg - Debug ]----------"
	@cd "pjmfg" && "$(MAKE)" -f  "pjmfg.mk"
clean:
	@echo "----------Cleaning project:[ pjmfg - Debug ]----------"
	@cd "pjmfg" && "$(MAKE)" -f  "pjmfg.mk" clean
